import { Icon } from '../common/Icon.jsx'

const money = new Intl.NumberFormat('en-PK', { maximumFractionDigits: 2 })
const labels = { pending: 'Awaiting seller', confirmed: 'Confirmed', fulfilled: 'Fulfilled', rejected: 'Declined', cancelled: 'Cancelled' }

export function OrderCard({ order, mode, onAction, busy }) {
  const sellerView = mode === 'sales'
  return <article className="commerce-order-card"><div className="commerce-order-head"><div><span className="card-kicker">{sellerView ? 'NEW SALE' : 'YOUR ORDER'}</span><h3>{order.productTitle}</h3></div><span className={`commerce-order-status ${order.status}`}>{labels[order.status]}</span></div><p className="commerce-order-person">{sellerView ? `Buyer: ${order.buyerName}` : `Seller: ${order.sellerName}`}</p><div className="commerce-order-facts"><span><strong>Quantity</strong>{order.quantity}</span><span><strong>Unit price</strong>Rs. {money.format(Number(order.unitPrice))}</span><span><strong>Total</strong>Rs. {money.format(Number(order.totalPrice))}</span></div><div className="commerce-order-delivery"><strong>Delivery details</strong><p>{order.deliveryAddress}</p><p>{order.contactPhone}</p>{order.buyerNote && <p>Note: {order.buyerNote}</p>}</div><div className="commerce-order-footer"><small>Order ID: {order.id}</small>{sellerView ? <div>{order.status === 'pending' && <><button type="button" className="secondary-button" disabled={busy} onClick={() => onAction(order, 'rejected')}>Decline</button><button type="button" className="primary-button" disabled={busy} onClick={() => onAction(order, 'confirmed')}>Confirm order</button></>}{order.status === 'confirmed' && <button type="button" className="primary-button" disabled={busy} onClick={() => onAction(order, 'fulfilled')}><Icon name="check" size={15}/> Mark fulfilled</button>}</div> : order.status === 'pending' && <button type="button" className="secondary-button" disabled={busy} onClick={() => onAction(order, 'cancelled')}>Cancel order</button>}</div></article>
}
